{% set name = "crowdsourcephoto" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crowdsourcephoto-{{ version }}.tar.gz
  sha256: 1e11bd29d2954acca4498d12a9d0156f6f25b0f6177ae06c1d503ae2e9302df2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - astropy
    - guppy3
    - keras
    - matplotlib-base
    - numpy
    - python >=3.6
    - scikit-image
    - scipy
    - tensorflow >=2.5

test:
  imports:
    - crowdsource
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/schlafly/crowdsource
  summary: Crowded field photometry pipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrew-saydjari
