{% set name = "crowdsourcephoto" %}
{% set version = "0.5.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crowdsourcephoto-{{ version }}.tar.gz
  sha256: 89b0fb098aa2793422aeef1dbf2112ff21adeea3c0ba39d40b6cfbe8e3e7d8f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - astropy
    - guppy3
    - keras
    - matplotlib-base
    - numpy
    - python >=3.6
    - scikit-image
    - scipy
    - tensorflow >=2.5

test:
  imports:
    - crowdsource
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/schlafly/crowdsource
  summary: Crowded field photometry pipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrew-saydjari
